### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by evanlu14** [minhhn2910/cuda-half2#1]
I way trying to run build `./build_clang.sh detect_half2_vars` and `./build_g++.sh detect_half2_vars`, both fails because of linking.

Here is the g++ build information:
```
➜  cuda-half2 git:(master) ✗ ./build_g++.sh detect_half2_vars                                                                                                                                                                                 
/home/zlu24/local/lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x75): undefined reference to `setupterm'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x98): undefined reference to `tigetnum'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa1): undefined reference to `set_curterm'
Process.cpp:(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa9): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
➜  cuda-half2 git:(master) ✗ 
```

I only compiled and installed LLVM 4.0 and clang 4.0 from [link](http://releases.llvm.org/download.html). Do I need to install extra packages?

Appreciate your help.

By the way, the link in the readme will lead to installing the newest version of LLVM, which is LLVM 9.0.

**Comment by evanlu14** [comment]
I solved this issue by adding `-ltinfo`  in the build_g++.sh.

**Comment by minhhn2910** [comment]
Please make pull request for your modification to help others who face the same issue, thanks
